### ISSUE TITLE
tox ci/cd is failing

### ISSUE THREAD

**Issue by RoryWirch** [red-hat-storage/rdopkg-tar#21] opened 2022-04-20 15:26 UTC
recently ( ~ month ) tox has failed due to a deprecated import in rdopkg/conf.py. This is causing tests to be marked as failures even though they work when ran locally.

**Comment by ktdreyer** [comment] 2022-05-26 19:00
The deprecation warning should not be fatal. Looks like the GitHub Action fails because `git commit -m Initial Import` is failing.

```
rdopkg.exception.CommandFailed: Command failed: ['git', 'commit', '-m', 'Initial import']
.tox/py39/lib/python3.9/site-packages/rdopkg/utils/cmd.py:112: CommandFailed
```

Not sure why, though

**Comment by ktdreyer** [comment] 2022-05-26 20:59
When I run the tests on my laptop, they pass, and when I run in GitHub Actions, the tests fail. `tox` does provide a certain level of isolation with individual Python virtualenvs, but clearly there's something different about my system on my laptop compared to GitHub's VM.

To debug this, I need to run it in an isolated environment that mimics the GitHub Actions VM.

## Reproducing locally

The GitHub Actions log output says it's running in Ubuntu 20.04 (Ubuntu "Focal"). Here's how I reproduced this in an Ubuntu Focal container:

```
podman run -it --rm ubuntu:focal

# Inside the container:
apt update && apt -y install git-core python3-venv

# Create a virtualenv to install tox:
python3 -m venv venv
. venv/bin/activate
pip install tox

# Clone out repository:
git clone https://github.com/red-hat-storage/rdopkg-tar -b wip-log-gitlab-user
cd rdopkg-tar

# Run the tests (Ubuntu 20.04 has Python 3.8 by default, so we'll just use that for convenience):
tox -e py38
```

This replicates the same `git commit -m "Initial import"` crash we see in GitHub Actions.

## Debugging with PDB

At this point, we need to change the code to dig deeper. I'm going to add a small change to `tox.ini` that allows me to easily get into Python's "PDB" (debugger): #22

With that change, I re-run the tests, and after the crash, pytest puts me at a pdb prompt:
```
        cout = _CommandOutput(out.decode('utf-8'))
        cout.stderr = err
        cout.return_code = prc.returncode
        cout.cmd = cmd_str
        if prc.returncode != 0:
            if log_fail:
                log_cmd_fail(cmd_str, cout)
            if fatal:
>               raise exception.CommandFailed(cmd=cmd, out=cout)
E               rdopkg.exception.CommandFailed: Command failed: ['git', 'commit', '-m', 'Initial import']

.tox/py38/lib/python3.8/site-packages/rdopkg/utils/cmd.py:112: CommandFailed
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> entering PDB >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

>>>>>>>>>>>>>>>>>> PDB post_mortem (IO-capturing turned off) >>>>>>>>>>>>>>>>>>>
> /root/rdopkg-tar/.tox/py38/lib/python3.8/site-packages/rdopkg/utils/cmd.py(112)run()
-> raise exception.CommandFailed(cmd=cmd, out=cout)
(Pdb)
```

Looking at the code right before `raise exception.CommandFailed...`, I see there is a lot of useful information assigned to this `cout` object. Let's start by printing the object itself:
```
(Pdb) cout
''
```

Yeah, that was not helpful. We can see `STDOUT` from our `git` invocation was simply an empty string. Next let's examine `STDERR`. The code assigns it to a property on `cout`, named `cout.stderr`, so let's print that:

```
(Pdb) print(cout.stderr)
b'\n*** Please tell me who you are.\n\nRun\n\n  git config --global user.email "you@example.com"\n  git config --global user.name "Your Name"\n\nto set your account\'s default identity.\nOmit --global to set the identity only in this repository.\n\nfatal: unable to auto-detect email address (got \'root@4f0520f38203.(none)\')'
```

This is a bit hard to read, let's decode the bytes so Python can print the newlines:

```
(Pdb) print(cout.stderr.decode('utf-8'))            

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'root@4f0520f38203.(none)')
```

## Understanding the root cause

There are a couple of ways that Git tries to determine a user's email address. If it cannot, it will bail out with this error message.

In othe words, Git shows this message whenever it's running for the first time in a new environment.

The reason this does not show up on my laptop is that I have a `/home/kdreyer/.gitconfig` file. But my Ubuntu container (and GitHub Actions VM) does not have this file. That why this test fails.

## Fixing the bug

There are a couple ways to fix this. *In general*, in most situations where you need to run `git commit` in an automated way, it's customary to set an email address *with an environment variable* rather than setting up `~/.gitconfig`. `man git-config` will show you the details about `user.name` and `user.email`.

The simplest thing is to just copy what rdopkg itself does. I grepped that tree for `EMAIL`, thinking there is probably some bit of code that sets `GIT_AUTHOR_EMAIL` or `EMAIL`. Sure enough, it's in [`tox.ini`](https://github.com/softwarefactory-project/rdopkg/blob/master/tox.ini).

So, to resolve this, you can add the following lines to `tox.ini` under `[testenv]`:

```
setenv =
  EMAIL=test@rdopkg-tar.tests
```

**Comment by ktdreyer** [comment] 2022-07-08 16:34
We've resolved this with the proper environment variables in `tox.ini` now.

**Closed by ktdreyer** 2022-07-08 16:34 UTC
Labels: bug
